// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/lighttx/v1beta1/lighttx.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 위치 정보
type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f16d2ab124c79c, []int{0}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

// 발전량 데이터
type SolarData struct {
	DeviceId             string    `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp            string    `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalEnergy          float64   `protobuf:"fixed64,3,opt,name=total_energy,json=totalEnergy,proto3" json:"total_energy,omitempty"`
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SolarData) Reset()         { *m = SolarData{} }
func (m *SolarData) String() string { return proto.CompactTextString(m) }
func (*SolarData) ProtoMessage()    {}
func (*SolarData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f16d2ab124c79c, []int{1}
}
func (m *SolarData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolarData.Unmarshal(m, b)
}
func (m *SolarData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolarData.Marshal(b, m, deterministic)
}
func (m *SolarData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolarData.Merge(m, src)
}
func (m *SolarData) XXX_Size() int {
	return xxx_messageInfo_SolarData.Size(m)
}
func (m *SolarData) XXX_DiscardUnknown() {
	xxx_messageInfo_SolarData.DiscardUnknown(m)
}

var xxx_messageInfo_SolarData proto.InternalMessageInfo

// REC 메타데이터
type RECMeta struct {
	FacilityId           string   `protobuf:"bytes,1,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	FacilityName         string   `protobuf:"bytes,2,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	TechnologyType       string   `protobuf:"bytes,4,opt,name=technology_type,json=technologyType,proto3" json:"technology_type,omitempty"`
	CapacityMw           string   `protobuf:"bytes,5,opt,name=capacity_mw,json=capacityMw,proto3" json:"capacity_mw,omitempty"`
	RegistrationDate     string   `protobuf:"bytes,6,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	CertifiedId          string   `protobuf:"bytes,7,opt,name=certified_id,json=certifiedId,proto3" json:"certified_id,omitempty"`
	IssueDate            string   `protobuf:"bytes,8,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	GenerationStartDate  string   `protobuf:"bytes,9,opt,name=generation_start_date,json=generationStartDate,proto3" json:"generation_start_date,omitempty"`
	GenerationEndDate    string   `protobuf:"bytes,10,opt,name=generation_end_date,json=generationEndDate,proto3" json:"generation_end_date,omitempty"`
	MeasuredVolume_MWh   string   `protobuf:"bytes,11,opt,name=measured_volume_MWh,json=measuredVolumeMWh,proto3" json:"measured_volume_MWh,omitempty"`
	RetiredDate          string   `protobuf:"bytes,12,opt,name=retired_date,json=retiredDate,proto3" json:"retired_date,omitempty"`
	RetirementPurpose    string   `protobuf:"bytes,13,opt,name=retirement_purpose,json=retirementPurpose,proto3" json:"retirement_purpose,omitempty"`
	Status               string   `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            string   `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RECMeta) Reset()         { *m = RECMeta{} }
func (m *RECMeta) String() string { return proto.CompactTextString(m) }
func (*RECMeta) ProtoMessage()    {}
func (*RECMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f16d2ab124c79c, []int{2}
}
func (m *RECMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RECMeta.Unmarshal(m, b)
}
func (m *RECMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RECMeta.Marshal(b, m, deterministic)
}
func (m *RECMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RECMeta.Merge(m, src)
}
func (m *RECMeta) XXX_Size() int {
	return xxx_messageInfo_RECMeta.Size(m)
}
func (m *RECMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RECMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RECMeta proto.InternalMessageInfo

// 트랜잭션 메시지
type MsgSendLightTx struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MsgSendLightTx_Original
	//	*MsgSendLightTx_Rec
	Payload              isMsgSendLightTx_Payload `protobuf_oneof:"payload"`
	Hash                 string                   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            string                   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Pubkey               string                   `protobuf:"bytes,6,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MsgSendLightTx) Reset()         { *m = MsgSendLightTx{} }
func (m *MsgSendLightTx) String() string { return proto.CompactTextString(m) }
func (*MsgSendLightTx) ProtoMessage()    {}
func (*MsgSendLightTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f16d2ab124c79c, []int{3}
}
func (m *MsgSendLightTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSendLightTx.Unmarshal(m, b)
}
func (m *MsgSendLightTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSendLightTx.Marshal(b, m, deterministic)
}
func (m *MsgSendLightTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendLightTx.Merge(m, src)
}
func (m *MsgSendLightTx) XXX_Size() int {
	return xxx_messageInfo_MsgSendLightTx.Size(m)
}
func (m *MsgSendLightTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendLightTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendLightTx proto.InternalMessageInfo

type isMsgSendLightTx_Payload interface {
	isMsgSendLightTx_Payload()
}

type MsgSendLightTx_Original struct {
	Original *SolarData `protobuf:"bytes,2,opt,name=original,proto3,oneof" json:"original,omitempty"`
}
type MsgSendLightTx_Rec struct {
	Rec *RECMeta `protobuf:"bytes,3,opt,name=rec,proto3,oneof" json:"rec,omitempty"`
}

func (*MsgSendLightTx_Original) isMsgSendLightTx_Payload() {}
func (*MsgSendLightTx_Rec) isMsgSendLightTx_Payload()      {}

func (m *MsgSendLightTx) GetPayload() isMsgSendLightTx_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgSendLightTx) GetOriginal() *SolarData {
	if x, ok := m.GetPayload().(*MsgSendLightTx_Original); ok {
		return x.Original
	}
	return nil
}

func (m *MsgSendLightTx) GetRec() *RECMeta {
	if x, ok := m.GetPayload().(*MsgSendLightTx_Rec); ok {
		return x.Rec
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MsgSendLightTx) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MsgSendLightTx_Original)(nil),
		(*MsgSendLightTx_Rec)(nil),
	}
}

// 응답 메시지
type MsgSendLightTxResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSendLightTxResponse) Reset()         { *m = MsgSendLightTxResponse{} }
func (m *MsgSendLightTxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendLightTxResponse) ProtoMessage()    {}
func (*MsgSendLightTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f16d2ab124c79c, []int{4}
}
func (m *MsgSendLightTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSendLightTxResponse.Unmarshal(m, b)
}
func (m *MsgSendLightTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSendLightTxResponse.Marshal(b, m, deterministic)
}
func (m *MsgSendLightTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendLightTxResponse.Merge(m, src)
}
func (m *MsgSendLightTxResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSendLightTxResponse.Size(m)
}
func (m *MsgSendLightTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendLightTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendLightTxResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Location)(nil), "cosmos.lighttx.v1beta1.Location")
	proto.RegisterType((*SolarData)(nil), "cosmos.lighttx.v1beta1.SolarData")
	proto.RegisterType((*RECMeta)(nil), "cosmos.lighttx.v1beta1.RECMeta")
	proto.RegisterType((*MsgSendLightTx)(nil), "cosmos.lighttx.v1beta1.MsgSendLightTx")
	proto.RegisterType((*MsgSendLightTxResponse)(nil), "cosmos.lighttx.v1beta1.MsgSendLightTxResponse")
}

func init() {
	proto.RegisterFile("cosmos/lighttx/v1beta1/lighttx.proto", fileDescriptor_d6f16d2ab124c79c)
}

var fileDescriptor_d6f16d2ab124c79c = []byte{
	// 750 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x4f, 0xeb, 0x46,
	0x14, 0xc5, 0x84, 0x92, 0x78, 0xcc, 0x47, 0x99, 0xb6, 0xc8, 0x4a, 0x69, 0x81, 0xf4, 0x0b, 0x51,
	0x25, 0x86, 0xb0, 0xea, 0x87, 0x54, 0x89, 0x82, 0x04, 0x12, 0xa9, 0x2a, 0x83, 0x8a, 0xd4, 0x8d,
	0x35, 0xb1, 0x2f, 0xce, 0x08, 0xdb, 0x63, 0xcd, 0x5c, 0x43, 0xb2, 0xed, 0x5f, 0xe8, 0xa2, 0xcb,
	0x2e, 0xfb, 0x37, 0xba, 0x7c, 0xfb, 0xf7, 0x0b, 0x9e, 0xf4, 0xfe, 0xc2, 0xdb, 0x3f, 0x79, 0xc6,
	0x8e, 0xe1, 0xe9, 0x45, 0x7a, 0x9b, 0xc4, 0xf7, 0x9c, 0x73, 0x8f, 0xef, 0x1d, 0x1f, 0x9b, 0x7c,
	0x1d, 0x0a, 0x95, 0x0a, 0xe5, 0x25, 0x3c, 0x9e, 0x20, 0x4e, 0xbd, 0x87, 0xe3, 0x31, 0x20, 0x3b,
	0xae, 0xeb, 0x41, 0x2e, 0x05, 0x0a, 0xba, 0x6d, 0x54, 0x83, 0x1a, 0xad, 0x54, 0xdd, 0x4f, 0x63,
	0x11, 0x0b, 0x2d, 0xf1, 0xca, 0x2b, 0xa3, 0xee, 0xee, 0xc4, 0x42, 0xc4, 0x09, 0x78, 0x2c, 0xe7,
	0x1e, 0xcb, 0x32, 0x81, 0x0c, 0xb9, 0xc8, 0x94, 0x61, 0x7b, 0x67, 0xa4, 0x73, 0x25, 0x42, 0x0d,
	0xd1, 0x2e, 0xe9, 0x24, 0x0c, 0x39, 0x16, 0x11, 0xb8, 0xd6, 0x9e, 0x75, 0x60, 0xf9, 0xf3, 0x9a,
	0xee, 0x10, 0x3b, 0x11, 0x59, 0x6c, 0xc8, 0x65, 0x4d, 0x36, 0x40, 0xef, 0x3f, 0x8b, 0xd8, 0xd7,
	0x22, 0x61, 0xf2, 0x8c, 0x21, 0xa3, 0x9f, 0x13, 0x3b, 0x82, 0x07, 0x1e, 0x42, 0xc0, 0x23, 0x6d,
	0x64, 0xfb, 0x1d, 0x03, 0x5c, 0x46, 0xa5, 0x11, 0xf2, 0x14, 0x14, 0xb2, 0x34, 0xd7, 0x46, 0xb6,
	0xdf, 0x00, 0x74, 0x9f, 0xac, 0xa1, 0x40, 0x96, 0x04, 0x90, 0x81, 0x8c, 0x67, 0x6e, 0x4b, 0xdf,
	0xc9, 0xd1, 0xd8, 0xb9, 0x86, 0xe8, 0xcf, 0xa4, 0x93, 0x54, 0x13, 0xbb, 0x2b, 0x7b, 0xd6, 0x81,
	0x33, 0xdc, 0x1b, 0xbc, 0xff, 0x40, 0x06, 0xf5, 0x66, 0xfe, 0xbc, 0xa3, 0xf7, 0xff, 0x0a, 0x69,
	0xfb, 0xe7, 0xbf, 0x8e, 0x00, 0x19, 0xdd, 0x25, 0xce, 0x1d, 0x0b, 0x79, 0xc2, 0x71, 0xd6, 0x4c,
	0x4a, 0x6a, 0xe8, 0x32, 0xa2, 0x5f, 0x91, 0xf5, 0xb9, 0x20, 0x63, 0x29, 0x54, 0xf3, 0xae, 0xd5,
	0xe0, 0x6f, 0x2c, 0x05, 0x7d, 0x6a, 0xf5, 0x3c, 0x2d, 0xb3, 0x6c, 0x5d, 0xd3, 0xef, 0xc8, 0x26,
	0x42, 0x38, 0xc9, 0x44, 0x22, 0xe2, 0x59, 0x80, 0xb3, 0x1c, 0xf4, 0xc8, 0xb6, 0xbf, 0xd1, 0xc0,
	0x37, 0xb3, 0x1c, 0xca, 0x51, 0x42, 0x96, 0xb3, 0xb0, 0xbc, 0x53, 0xfa, 0xe8, 0x7e, 0x64, 0x46,
	0xa9, 0xa1, 0xd1, 0x23, 0xfd, 0x9e, 0x6c, 0x49, 0x88, 0xb9, 0x42, 0xa9, 0x9d, 0x83, 0x88, 0x21,
	0xb8, 0xab, 0x5a, 0xf6, 0xf1, 0x53, 0xe2, 0x8c, 0x21, 0x94, 0xa7, 0x18, 0x82, 0x44, 0x7e, 0xc7,
	0x21, 0x2a, 0x37, 0x6b, 0x6b, 0x9d, 0x33, 0xc7, 0x2e, 0x23, 0xfa, 0x05, 0x21, 0x5c, 0xa9, 0x02,
	0x8c, 0x51, 0xc7, 0x3c, 0x07, 0x8d, 0x68, 0x87, 0x21, 0xf9, 0x2c, 0x2e, 0x1f, 0x81, 0xb9, 0x99,
	0x42, 0x26, 0xd1, 0x28, 0x6d, 0xad, 0xfc, 0xa4, 0x21, 0xaf, 0x4b, 0x4e, 0xf7, 0x0c, 0xc8, 0x13,
	0x38, 0x80, 0x2c, 0x32, 0x1d, 0x44, 0x77, 0x6c, 0x35, 0xd4, 0x79, 0x16, 0xd5, 0xfa, 0x14, 0x98,
	0x2a, 0x24, 0x44, 0xc1, 0x83, 0x48, 0x8a, 0x14, 0x82, 0xd1, 0xed, 0xc4, 0x75, 0x8c, 0xbe, 0xa6,
	0xfe, 0xd0, 0xcc, 0xe8, 0x76, 0x52, 0x6e, 0x25, 0x01, 0x79, 0x29, 0xd7, 0xc6, 0x6b, 0x66, 0xab,
	0x0a, 0xd3, 0x96, 0x7d, 0x42, 0x4d, 0x99, 0x42, 0x86, 0x41, 0x5e, 0xc8, 0x5c, 0x28, 0x70, 0xd7,
	0x8d, 0x63, 0xc3, 0xfc, 0x6e, 0x08, 0xba, 0x4d, 0x56, 0x15, 0x32, 0x2c, 0x94, 0xbb, 0xa1, 0x25,
	0x55, 0xf5, 0x3c, 0xa3, 0x9b, 0xef, 0x64, 0xb4, 0xf7, 0xc6, 0x22, 0x1b, 0x23, 0x15, 0x5f, 0x43,
	0x16, 0x5d, 0x95, 0x81, 0xbb, 0x99, 0x52, 0x97, 0xb4, 0x43, 0x09, 0x0c, 0x85, 0xac, 0x52, 0x54,
	0x97, 0xf4, 0x17, 0xd2, 0x11, 0x92, 0xc7, 0x3c, 0x63, 0x89, 0x4e, 0x8f, 0x33, 0xdc, 0x5f, 0x94,
	0xd6, 0xf9, 0x0b, 0x74, 0xb1, 0xe4, 0xcf, 0x9b, 0xe8, 0x09, 0x69, 0x49, 0x08, 0x75, 0xb2, 0x9c,
	0xe1, 0xee, 0xa2, 0xde, 0x2a, 0xd2, 0x17, 0x4b, 0x7e, 0xa9, 0xa6, 0x94, 0xac, 0x4c, 0x98, 0x9a,
	0x54, 0x61, 0xd3, 0xd7, 0xe5, 0x52, 0x8a, 0xc7, 0x19, 0xc3, 0x42, 0x42, 0x15, 0xb0, 0x06, 0x28,
	0x8f, 0x22, 0x2f, 0xc6, 0xf7, 0x30, 0xab, 0x42, 0x55, 0x55, 0xa7, 0x36, 0x69, 0xe7, 0x6c, 0x96,
	0x08, 0x16, 0xf5, 0x8e, 0xc8, 0xf6, 0xf3, 0xb5, 0x7d, 0x50, 0xb9, 0xc8, 0xcc, 0x39, 0x4a, 0x50,
	0x45, 0x82, 0xd5, 0xf6, 0x55, 0x35, 0xfc, 0xd7, 0x22, 0xad, 0x91, 0x8a, 0xe9, 0x3f, 0x16, 0x71,
	0x9e, 0x1e, 0xd7, 0xb7, 0x8b, 0xd6, 0x78, 0xee, 0xdf, 0x1d, 0x7c, 0x98, 0xae, 0x9e, 0xa3, 0x77,
	0xf4, 0xd7, 0xcb, 0xd7, 0x7f, 0x2f, 0x1f, 0xf6, 0xbe, 0xf1, 0x16, 0x7c, 0x47, 0x15, 0x64, 0x51,
	0x5f, 0x83, 0x7d, 0x9c, 0xfe, 0x68, 0x1d, 0x9e, 0xfe, 0xf0, 0xe2, 0xd5, 0x97, 0x4b, 0x7f, 0x9e,
	0xc4, 0x1c, 0x27, 0xc5, 0x78, 0x10, 0x8a, 0xb4, 0xee, 0x34, 0x7f, 0x7d, 0x15, 0xdd, 0x7b, 0x53,
	0x63, 0x13, 0xe0, 0xd4, 0x2b, 0xdf, 0x60, 0xf5, 0x93, 0xfe, 0x1d, 0xaf, 0xea, 0x0f, 0xe8, 0xc9,
	0xdb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0xde, 0x84, 0x53, 0xb4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SendLightTx(ctx context.Context, in *MsgSendLightTx, opts ...grpc.CallOption) (*MsgSendLightTxResponse, error)
}

type msgClient struct {
	cc *grpc.ClientConn
}

func NewMsgClient(cc *grpc.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendLightTx(ctx context.Context, in *MsgSendLightTx, opts ...grpc.CallOption) (*MsgSendLightTxResponse, error) {
	out := new(MsgSendLightTxResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lighttx.v1beta1.Msg/SendLightTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SendLightTx(context.Context, *MsgSendLightTx) (*MsgSendLightTxResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendLightTx(ctx context.Context, req *MsgSendLightTx) (*MsgSendLightTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLightTx not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendLightTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendLightTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendLightTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lighttx.v1beta1.Msg/SendLightTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendLightTx(ctx, req.(*MsgSendLightTx))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.lighttx.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLightTx",
			Handler:    _Msg_SendLightTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/lighttx/v1beta1/lighttx.proto",
}
